config/routes.rb
Rails.application.routes.draw do
  resources :hangouts
  resources :events
  devise_for :users, controllers: { registrations: "registrations" }
  devise_scope :user do
   put "/users/update_about", to: "registrations#update_about"
   post "/events/join/:id", to: "events#join"
  end
  root to: 'pages#home'

end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :user
  has_many :hangouts
  has_many :users, through: :hangouts
end

app/models/hangout.rb
class Hangout < ActiveRecord::Base
  belongs_to :user
  belongs_to :event
end

app/models/user.rb
class User < ActiveRecord::Base
  include Gravtastic
  gravtastic :deafult => "wavatar"
  has_many :events
  has_many :hangouts

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :email, format: { with: /\w+\@\w+\.edu\.?\w*/,
    message: "Please use your .edu email" }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy, :join]

  # GET /events
  # GET /events.json
  def index
    @events = Event.all
  end

  # GET /events/1
  # GET /events/1.json
  def show
    @user = User.find(@event.user_id)
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  def join
    Hangout.new(user_id: current_user.id, event_id: @event.id)
    @event.joined += 1
    redirect_to root_path, notice: 'Event was successfully Joined.'
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)
    @event.user_id = current_user.id
    @event.joined = 0
    respond_to do |format|
      if @event.save
        format.html { redirect_to root_path, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: root_path, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:user_id, :what, :when, :where, :latitude, :longitude, :needed, :joined)
    end
end

app/controllers/hangouts_controller.rb
class HangoutsController < ApplicationController
  before_action :set_hangout, only: [:show, :edit, :update, :destroy]

  # GET /hangouts
  # GET /hangouts.json
  def index
    @hangouts = Hangout.all
  end

  # GET /hangouts/1
  # GET /hangouts/1.json
  def show
  end

  # GET /hangouts/new
  def new
    @hangout = Hangout.new
  end

  # GET /hangouts/1/edit
  def edit
  end

  # POST /hangouts
  # POST /hangouts.json
  def create
    @event = Event.find(params[:hangout][:event])
    @user = User.find(params[:hangout][:user])
    @hangout = Hangout.new(user: @user, event: @event)

    respond_to do |format|
      if params[:hangout][:user] == @event.user_id
        format.html { redirect_to root_path, notice: 'You\'re the creator of the event' }
      elsif @event.joined == @event.needed
        format.html { redirect_to root_path, notice: 'Event is full' }
      elsif !Hangout.where(event: @event, user: @user).first.nil?
        format.html { redirect_to root_path, notice: 'You\'re already joined' }
      elsif @hangout.save
        @hangout.event.joined = @hangout.event.joined + 1
        @hangout.event.save
        format.html { redirect_to root_path, notice: 'Event Joined!' }
        format.json { render :show, status: :created, location: @hangout }
      else
        format.html { render :new }
        format.json { render json: @hangout.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /hangouts/1
  # PATCH/PUT /hangouts/1.json
  def update
    respond_to do |format|
      if @hangout.update(hangout_params)
        format.html { redirect_to @hangout, notice: 'Hangout was successfully updated.' }
        format.json { render :show, status: :ok, location: @hangout }
      else
        format.html { render :edit }
        format.json { render json: @hangout.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /hangouts/1
  # DELETE /hangouts/1.json
  def destroy
    @hangout.destroy
    respond_to do |format|
      format.html { redirect_to hangouts_url, notice: 'Hangout was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_hangout
      @hangout = Hangout.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def hangout_params
      params.require(:hangout).permit(:user, :event)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @user = User.new
    @user = current_user if user_signed_in?
    @event = Event.new
    @events = Event.all
    @hangout = Hangout.new
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  before_action :authenticate_user!
  def new
    super
  end

  def create
    super
    temp = @user.email.scan(/\w+\.edu/).first
    @user.uni = temp[0..-5].upcase unless temp.nil?
    @user.save
  end

  def update
    super
  end

  def update_about
    @user = current_user
    @user.update_attributes!(:about => about_update_params[:about])
    @user.save
    redirect_to root_path
  end

  def about_update_params
    params.require(:user).permit(:about)
  end
  private

  def sign_up_params
    params.require(:user).permit(:first, :last, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:first, :last, :password, :password_confirmation, :current_password, :about)
  end



end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/hangouts_helper.rb
module HangoutsHelper
end

app/views/events/_form.html.erb
<%= simple_form_for(@event, remote: true) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.hidden_field :what, input_html: {id: "formWant"}%>
    <%= f.input :when %>
    <%= f.input :where %>
    <%= f.input :needed %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Editing Event</h1>

<%= render 'form' %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Events</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>What</th>
      <th>When</th>
      <th>Where</th>
      <th>Latitude</th>
      <th>Longitude</th>
      <th>Needed</th>
      <th>Joined</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @events.each do |event| %>
      <tr>
        <td><%= event.user.first + " " + event.user.last %></td>
        <td><%= event.what %></td>
        <td><%= event.when %></td>
        <td><%= event.where %></td>
        <td><%= event.latitude %></td>
        <td><%= event.longitude %></td>
        <td><%= event.needed %></td>
        <td><%= event.joined %></td>
        <td><%= link_to 'Show', event %></td>
        <td><%= link_to 'Edit', edit_event_path(event) %></td>
        <td><%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Event', new_event_path %>

app/views/events/new.html.erb
<h1>New Event</h1>

<%= render 'form' %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= event.user.first + " " + event.user.last  %>
</p>

<p>
  <strong>What:</strong>
  <%= @event.what %>
</p>

<p>
  <strong>When:</strong>
  <%= @event.when %>
</p>

<p>
  <strong>Where:</strong>
  <%= @event.where %>
</p>

<p>
  <strong>Latitude:</strong>
  <%= @event.latitude %>
</p>

<p>
  <strong>Longitude:</strong>
  <%= @event.longitude %>
</p>

<p>
  <strong>Needed:</strong>
  <%= @event.needed %>
</p>

<p>
  <strong>Joined:</strong>
  <%= @event.joined %>
</p>

<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'Back', events_path %>

app/views/hangouts/_form.html.erb
<%= simple_form_for(@hangout) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.association :user %>
    <%= f.association :event %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/hangouts/edit.html.erb
<h1>Editing Hangout</h1>

<%= render 'form' %>

<%= link_to 'Show', @hangout %> |
<%= link_to 'Back', hangouts_path %>

app/views/hangouts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Hangouts</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Event</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @hangouts.each do |hangout| %>
      <tr>
        <td><%= hangout.user %></td>
        <td><%= hangout.event %></td>
        <td><%= link_to 'Show', hangout %></td>
        <td><%= link_to 'Edit', edit_hangout_path(hangout) %></td>
        <td><%= link_to 'Destroy', hangout, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Hangout', new_hangout_path %>

app/views/hangouts/new.html.erb
<h1>New Hangout</h1>

<%= render 'form' %>

<%= link_to 'Back', hangouts_path %>

app/views/hangouts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @hangout.user %>
</p>

<p>
  <strong>Event:</strong>
  <%= @hangout.event %>
</p>

<%= link_to 'Edit', edit_hangout_path(@hangout) %> |
<%= link_to 'Back', hangouts_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>I Want To</title>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
  </body>
</html>

app/views/pages/_event_form.html.erb
<%= simple_form_for(@event) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.hidden_field :what %>
    <%= f.input :when %>
    <%= f.input :where %>
    <%= f.input :needed %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/pages/_event_modal.html.erb
<div class="modal fade" id="newEvent">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">Event Details</h4>
      </div>
      <div class="modal-body">
        <%= render 'event_form' %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

app/views/pages/_main.html.erb
<div class="container-fluid" id="main" style="background-color:rgba(50,200,200,1)">
  <div class="row">
    <div class="col-xs-8">
      <h1>I want to <input type="text" id="want" placeholder="Fuck Bitches" ><button id="doit" data-toggle="modal" data-target="#newEvent">Do it</button></h1>
      <%= render 'event_modal' %>
      <% @events.each do |e| %>
        <div class="cardx">
          <ul>
            <li><%= image_tag e.user.gravatar_url %></li>
            <li><%= e.user.first + " wants to " + e.what %></li>
            <li>Where: <%= e.where %></li>
            <li>When: <%= e.when %></li>
            <li>Joined: <%= e.joined %> / <%= e.needed %></li>
          </ul>
          <%= simple_form_for(@hangout) do |f| %>
            <%= f.error_notification %>

            <div class="form-inputs">
              <%= f.hidden_field :user, :value => current_user.id %>
              <%= f.hidden_field :event,  :value => e.id %>
            </div>

            <div class="form-actions">
              <%= f.button :submit, "Join In" %>
            </div>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/pages/_sidebar.html.erb
<div class="container" id="side">
  <div class="row">
    <div class="col-xs-3">
      <ul>
        <li><%= image_tag current_user.gravatar_url %></li>
        <li><%= current_user.first + ' ' + current_user.last %></li>
        <li><%= current_user.email %></li>
        <li><%= current_user.uni %></li>
        <li><%= current_user.about %></li>
        <%= simple_form_for(@user, url: 'users/update_about', html: { method: :put }) do |f| %>
          <%= f.error_notification %>

          <div class="form-inputs">
          <%= f.input :about, required: true, autofocus: true %>
          </div>

          <div class="form-actions">
            <%= f.button :submit, "Update" %>
          </div>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/pages/home.html.erb
<%= render 'sidebar' if user_signed_in?%>
<%= render 'main' if user_signed_in?%>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar-wagon">
  <div class="container navbar-wagon-container">

    <a href="">
      <%= image_tag "logo.png" %>
    </a>

    <div class="navbar-wagon-pusher"></div>

    <form action="" class="navbar-wagon-search hidden-xs hidden-sm">
      <input type="text" class="navbar-wagon-search-input" placeholder="Search something">
      <button type="submit" class="navbar-wagon-search-btn">
        <i class="fa fa-search"></i>
      </button>
    </form>
    <hr class="hidden-xs hidden-sm">
    <% if user_signed_in? %>
      <%= link_to "#", class: "navbar-wagon-item navbar-wagon-link hidden-xs" do %>
        <div class="icon-badge-container">
          <i class="fa fa-envelope-o"></i>
          <div class="icon-badge icon-badge-blue">3</div>
        </div>
      <% end %>
      <hr>
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <%= image_tag current_user.gravatar_url, class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-user"></i> <%= t ".profile", default: "Profile" %>
              <% end %>
            </li>
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-home"></i>  <%= t ".profile", default: "Home" %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t ".sign_out", default: "Log out" %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    <% else %>
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <% end %>
    <hr>
    <%= link_to t(".top_call_to_action", default: "Post stuff"), "#", class: "navbar-wagon-item navbar-wagon-button btn" %>
  </div>
</nav>